---
- name: Create the instance
  uri:
    url: '{{ morpheus_appliance_url }}/api/instances'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
    method: POST
    body:
      "{{ lookup('template', 'create-instance.j2') | to_yaml }}"
    body_format: json
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: create_morpheus_instance
  when:
    - morpheus_api_token is defined
    - ZONEID is defined
    - INSTANCE_NAME is defined
    - INSTANCE_GROUP_ID is defined
    - INSTANCE_TYPE is defined
    - INSTANCE_LAYOUT_ID is defined
    - INSTANCE_PLAN is defined

