---
- name: RESTORE THE MONGODB JSON
  hosts: localhost
  vars:
    # MONGODB SOURCE FILE VARIBLES
    MONGO_RESTORE_FROM_LOCALHOST_SERVER: false
    MONGO_RESTORE_FROM_REMOTE_SERVER: false
    MONGO_HOST: mongodb1.example.net
    MONGO_USERNAME: user
    MONGO_PASSWORD: password
    MONGO_PORT: 27017
    MONGO_DIR: /mnt/backup/mongodump
    # COPY THE FILES LOCALHOST TO REMOTE HOST VARIBLES
    SOURCE_FILE_LOCATION: /opt/backup/mongodump
    DEST_FILE_LOCATION: /mnt/backup/mongodump
  tasks:
  
  - name: COPY THE FOLDER localhost server to MONGO
    copy:
      src: {{ SOURCE_FILE_LOCATION }}
      dest: {{ DEST_FILE_LOCATION }}
      remote_src: yes

  - name: RESTORE THE MONGo DOCUMENTS
    shell: "mongodump --host={{ MONGO_USERNAME }} --port={{ MONGO_PORT }} --username={{ MONGO_USERNAME }} --password={{ MONGO_PASSWORD }} --out={{ MONGO_DIR }}"
    register: _RESTORE_RESULT
    when: MONGO_RESTORE_FROM_REMOTE_SERVER

  - name: DEBUG THE RESULT
    debug:
      msg: "{{ _RESTORE_RESULT }}"
    when: MONGO_RESTORE_FROM_REMOTE_SERVER

  - name: RESTORE THE MONGo DOCUMENTS
    shell: "mongodump --port=27017 --username={{ MONGO_USERNAME }} --password={{ MONGO_PASSWORD }} --out={{ MONGO_DIR }}"
    register: _RESTORE_LOCALHOST_RESULT
    when: MONGO_RESTORE_FROM_LOCALHOST_SERVER

  - name: DEBUG THE RESULT
    debug:
      msg: "{{ _RESTORE_LOCALHOST_RESULT }}"
    when: MONGO_RESTORE_FROM_LOCALHOST_SERVER
