pipelines:
  default:
    - step:
        name: development environment
        script:
          - echo "Development environment deployment stage"
          - sudo apt update
          - sudo apt install sshpass rsync openssh-server -y
          - rsync -avzu -e "ssh -i automation_key" * $USERNAME@$IPADDRESS:/srv/apache/public_html_jenkins/www_new/

  branches:
    master:
      - step:
          name: production environment
          deployment: Production
          script:
            - echo "production environment deployment stage"
            - sudo apt update
            - sudo apt install sshpass rsync openssh-server -y
            - rsync -avzu -e "ssh -i automation_key" * $USERNAME@$IPADDRESS:/srv/apache/public_html_jenkins/www_new/

    test:
      - step:
          name: test environment
          deployment: Test
          script:
            - echo "test environment deployment stage"
            - sudo apt update
            - sudo apt install sshpass rsync openssh-server -y
            - rsync -avzu -e "ssh -i automation_key" * $USERNAME@$IPADDRESS:/srv/apache/public_html_jenkins/www_new/

# https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/
# https://bitbucket.org/blog/build-trust-in-your-deployment-workflow-with-deployment-permissions
# https://support.atlassian.com/bitbucket-cloud/docs/pipeline-triggers/
