pipelines:
  default:
    - step:
        name: development environment
        script:
          - echo "Development environment deployment stage"
          - sudo apt update
          - sudo apt install sshpass rsync openssh-server -y

  branches:
    master:
      - step:
          name: production environment
          deployment: Production
          script:
            - echo "production environment deployment stage"
            - sudo apt update
            - sudo apt install sshpass rsync openssh-server -y

    test:
      - step:
          name: test environment
          deployment: Test
          script:
            - echo "test environment deployment stage"
            - sudo apt update
            - sudo apt install sshpass rsync openssh-server -y

