version: 0.2
phases:
  pre_build:
    commands:
      - OFFICIAL_IMAGE=nginx
      - ECR=456774515540.dkr.ecr.eu-west-1.amazonaws.com/common-images
      - destImage=$ECR:$OFFICIAL_IMAGE
      - echo "PASSWORD@123" | docker login -u jjino --password-stdin
      - docker pull $OFFICIAL_IMAGE
      - docker logout
  build:
    commands:
      - echo Build started on `date`
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker tag $OFFICIAL_IMAGE $destImage
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $destImage
