
version: 0.2
env:
  variables:
    OFFICIAL_IMAGE: "nginx"
    ECR: "456774515540.dkr.ecr.us-east-1.amazonaws.com/node"
phases:
  pre_build:
    commands:
      - destImage=$ECR:$OFFICIAL_IMAGE
      - docker pull $OFFICIAL_IMAGE
    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - echo Build started on `date`
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker tag $OFFICIAL_IMAGE $destImage
      - docker push $destImage
    finally:
      - echo tag completed
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir target
      - aws ecr describe-image-scan-findings --repository-name node --image-id imageTag=node --region us-east-1 > target/result.json
    finally:
      - echo image reports generated....

reports:
  report-group-name-or-arn:
    files:
      - result.json
    base-directory: target
    discard-paths: no
    file-format: report-format

# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
