version: 0.2
env:
  variables:
    OFFICIAL_IMAGE: "httpd"
    ECR_REPO_NAME: node
    ECR_FULL_URL: "456774515540.dkr.ecr.us-east-1.amazonaws.com/node"
phases:
  pre_build:
    commands:
      - destImage=$ECR_FULL_URL:$OFFICIAL_IMAGE
      - docker pull $OFFICIAL_IMAGE
    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - echo Build started on `date`
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker tag $OFFICIAL_IMAGE $destImage
      - docker push $destImage
    finally:
      - echo tag completed
  post_build:
    commands:
      - echo Build completed on `date`
      - aws ecr describe-image-scan-findings --repository-name $ECR_REPO_NAME --image-id imageTag=$OFFICIAL_IMAGE --region us-east-1
    finally:
      - echo image reports generated....
