
version: 0.2
env:
  variables:
    REGION: "us-east-1"
    DOCKER_IMAGE_NAME: "redis"
    ECR_REPO_NAME: "node"
    ECR_REPO_URL: "456774515540.dkr.ecr.us-east-1.amazonaws.com"
phases:
  pre_build:
    commands:
      - destImage=$ECR_REPO_URL/$ECR_REPO_NAME:$DOCKER_IMAGE_NAME
      - docker pull $DOCKER_IMAGE_NAME
    finally:
      - echo This always runs even if the update or install command fails 
  build:
    commands:
      - echo Build started on `date`
      - $(aws ecr get-login --region $REGION --no-include-email)
      - docker tag $DOCKER_IMAGE_NAME $destImage
      - docker push $destImage
    finally:
      - echo tag completed
  post_build:
    commands:
      - echo Build completed on `date`
      - aws ecr describe-image-scan-findings --repository-name $ECR_REPO_NAME --image-id imageTag=$DOCKER_IMAGE_NAME --region $REGION
    finally:
      - echo image reports generated.
