---
- hosts: all
  tasks:
  - name: update the repositary
    apt:
      update_cache: yes
  - name: install the apache packages
    apt:
      name: apache2
      state: present
  - name: start the apache2 service
    service:
      name: apache2
      state: started
      enabled: yes
