---
# tasks file for get-group
- name: Create the instance type
  uri:
    url: '{{ morpheus_appliance_url }}/api/groups'
    headers:
        Authorization: "BEARER {{ morpheus_api_token }}"
    method: GET
    force_basic_auth: yes
    return_content: true
    validate_certs: false
  register: create_morpheus_instance_type
  when:
    - INSTANCE_TYPE_NAME is defined
    - morpheus_api_token is defined